import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Franchise Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`antialiased bg-gray-50 text-slate-800 font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
